### PR TITLE
Patch for compatibility with Coinbase-ruby v4 gem and Coinbase v2 API

### PR DESCRIPTION
**Pull request by cusackalex**
+ Remove coinbase gem v2.0 runtime dependency 
+ Remove SSL as Whitelisted_cert_store does not exist in Coinbase-ruby v4 gem 

Gem now compatible with Coinbase v2 API and Coinbase-ruby v4 gem.

### CODE REVIEW

**Comment by jorilallo** [comment]
Thanks for this. We'll actually need to add cert pinning to new v4 of the coinbase gem. Once we have added that I'll update this library to use the new gem

**Comment by cusackalex** [comment]
@jorilallo sweet, thanks! Figured the cert pinning would get added soon. 
The v2 api is killer by the way, great work :raised_hands:

**Comment by jorilallo** [comment]
@cusackalex Thanks! More updates and goodies coming soon :ok_hand:

**Comment by aianus** [comment]
v2.0.0 of the gem includes this functionality

**Pull request closed without merging**
